Repository BE-Archive/Algorithm-Study, pull requests merged in 2024-06, with the labels that each got.

#485 [240530] BOJ 17609 회문
  hyunseok0314/Week_19/BOJ_17609_회문.py
Labels: 문자열

#482 [240530] BOJ 17609 회문
  wnso-kim/Week_19/BOJ_17609_회문/BOJ_17609_회문.java
  wnso-kim/Week_19/BOJ_17609_회문/BOJ_17609_회문.md
Labels: 투포인터

#483 [240530] BOJ 17609 회문
  seoyoung059/Week_19/BOJ_17609/BOJ_17609.java
  seoyoung059/Week_19/BOJ_17609/BOJ_17609.md
Labels: 투포인터, 재귀

#484 [240530] BOJ 17609 회문
  sickbirdd/Week_19/BOJ_17609_회문.java
  sickbirdd/Week_19/BOJ_17609_회문.md
Labels: 투포인터

#486 [240530] BOJ 17609 회문
  l-umi/Week_19/BOJ_17609_회문.py
Labels: 문자열

#487 [240530] BOJ 17609 회문
  ys4512558/Week_19/BOJ_17609_회문/BOJ_17609_회문.java
  ys4512558/Week_19/BOJ_17609_회문/BOJ_17609_회문.md
Labels: 투포인터

#488 [240530] BOJ 17609 회문
  sjhlko/week19/BOJ_17609_회문/BOJ_17609_회문.java
Labels: 투포인터

#489 [240530] BOJ 17609 회문
  u1qns/Week_19/BOJ_17609_ 회문.cpp
Labels: 투포인터

#490 [240530] BOJ 17609 회문
  ezeun/Week_19/BOJ_17609_회문/BOJ_17609_회문.cpp
  ezeun/Week_19/BOJ_17609_회문/BOJ_17609_회문.md
Labels: 투포인터

#491 [240530] BOJ 17609 회문
  yunva17/Week_19/BOJ_17609_회문/BOJ_17609_회문.js
Labels: 투포인터

#493 [240530] BOJ 17609 회문
  violetadieu/Week_19/BOJ_17609_회문.py
Labels: 투포인터

#492 [240530] BOJ 17609 회문
  trankill1127/w19/BOJ_17609.java
Labels: 투포인터

#495 [240601] BOJ 1461 도서관
  hyunseok0314/Week_19/BOJ_1461_도서관.java
Labels: 그리디 알고리즘

#502 [240601] BOJ 1461 도서관
  trankill1127/w19/BOJ_1461.java
  trankill1127/w19/BOJ_21278.java
Labels: 그리디 알고리즘

#499 [240601] BOJ 1461 도서관
  ys4512558/Week_19/BOJ_1461_도서관/BOJ_1461_도서관.java
  ys4512558/Week_19/BOJ_1461_도서관/BOJ_1461_도서관.md
Labels: 그리디 알고리즘

#515 [240601] BOJ 1461 도서관
  ezeun/Week_19/BOJ_1461_도서관/BOJ_1461_도서관.cpp
  ezeun/Week_19/BOJ_1461_도서관/BOJ_1461_도서관.md
Labels: 그리디 알고리즘

#516 [240602] BOJ 21278 호석이 두 마리 치킨
  u1qns/Week_19/BOJ_21278_호석이두마리치킨.cpp
Labels: 조합, 플로이드-워셜

#538 [240607] BOJ 17208 카우버거 알바생
  ezeun/Week_20/BOJ_17208_카우버거알바생/BOJ_17208_카우버거알바생.cpp
  ezeun/Week_20/BOJ_17208_카우버거알바생/BOJ_17208_카우버거알바생.md
Labels: DP

#540 [240610] BOJ 3980 선발 명단
  seoyoung059/Week_21/BOJ_3980/BOJ_3980.java
  seoyoung059/Week_21/BOJ_3980/BOJ_3980.md
Labels: 재귀

#541 [240610] BOJ 3980 선발 명단
  ys4512558/Week_21/BOJ_3980_선발명단/BOJ_3980_선발명단.java
  ys4512558/Week_21/BOJ_3980_선발명단/BOJ_3980_선발명단.md
Labels: 백트래킹

#542 [240610] BOJ 3980 선발명단
  u1qns/Week_21/BOJ_3980_선발명단.cpp
Labels: 백트래킹

#543 [240610] BOJ 3980 선발명단
  ezeun/Week_21/BOJ_3980_선발명단/BOJ_3980_선발명단.cpp
  ezeun/Week_21/BOJ_3980_선발명단/BOJ_3980_선발명단.md
Labels: 백트래킹

#544 [240610] BOJ 3980 선발 명단
  trankill1127/w21/BOJ_3980.java
Labels: 백트래킹

#545 [240610] BOJ 3980 선발 명단
  sickbirdd/Week_21/BOJ_3980_선발 명단.java
  sickbirdd/Week_21/BOJ_3980_선발 명단.md
Labels: 백트래킹

#546 [240610] BOJ 3980 선발 명단
  hyunseok0314/Week_20/BOJ_17208_카우버거_알바생.py
  hyunseok0314/Week_20/BOJ_1756_피자_굽기.java
  hyunseok0314/Week_21/BOJ_3980_선발_명단.java
Labels: 백트래킹

#547 [240610] BOJ 3980 선발 명단
  l-umi/Week_21/BOJ_3980_선발_명단.py
Labels: 완전 탐색

#548 [240610] BOJ 3980 선발 명단
  yunva17/Week_21/BOJ_3980_선발명단/BOJ_3980_선발명단.js
Labels: 백트래킹

#549 [240610] BOJ 3980 선발 명단
  sjhlko/week21/BOJ_3980/BOJ_3980_선발명단.java
Labels: 완전 탐색

#550 [240610] BOJ 3980 선발 명단
  violetadieu/Week_21/BOJ_3980_선발명단.py
Labels: 백트래킹

#554 [240611] PGS 산 모양 타일링
  l-umi/Week_21/PGS_산_모양_타일링.py
Labels: 그리디 알고리즘

#555 [240611] PGS 산 모양 타일링
  hyunseok0314/Week_21/PSG_산_모양_타일링.py
Labels: DP

#551 [240610] BOJ 3980 선발 명단
  wnso-kim/Week_21/BOJ_3980_선발명단/BOJ_3980_선발명단.java
  wnso-kim/Week_21/BOJ_3980_선발명단/BOJ_3980_선발명단.md
Labels: DFS, 완전 탐색

#556 [240611] PGS 산 모양 타일링
  sickbirdd/Week_21/PGS_산_모양_타일링.java
  sickbirdd/Week_21/PGS_산_모양_타일링.md
Labels: DP

#560 [240611] PGS 산 모양 타일링
  ezeun/Week_21/PGS_산모양타일링/PGS_산모양타일링.cpp
  ezeun/Week_21/PGS_산모양타일링/PGS_산모양타일링.md
  ezeun/Week_21/PGS_산모양타일링/image.png
Labels: DP

#553 [240611] PGS 산 모양 타일링
  seoyoung059/Week_21/PGS_산_모양_타일링/PGS_산_모양_타일링.java
  seoyoung059/Week_21/PGS_산_모양_타일링/PGS_산_모양_타일링.md
Labels: DP

#557 [240611] PGS 산 모양 타일링
  u1qns/Week_21/PGS_산모양타일링.cpp
Labels: DP

#568 [240612] BOJ 1661 다솜이의 신발가게
  yunva17/Week_21/BOJ_1661_다솜이의신발가게/BOJ_1661_다솜이의신발가게.js
Labels: 도전중

#573 [240613] BOJ 16118 달빛 여우
  sjhlko/week21/BOJ_10711/BOJ_10711_모래성.java
  sjhlko/week21/BOJ_16118/BOJ_16118_달빛여우.java
Labels: 다익스트라

#576 [240614] BOJ 10711 모래성
  ezeun/Week_21/BOJ_10711_모래성/BOJ_10711_모래성.cpp
  ezeun/Week_21/BOJ_10711_모래성/BOJ_10711_모래성.md
  ezeun/Week_21/BOJ_10711_모래성/image-1.png
  ezeun/Week_21/BOJ_10711_모래성/image.png
Labels: BFS

#579 [240613] BOJ 16118 달빛 여우
  hyunseok0314/Week_21/BOJ_16118_달빛_여우.cpp
Labels: 다익스트라

#581 [240614] BOJ 10711 모래성
  u1qns/Week_21/BOJ_10711_모래성.java
Labels: BFS

#582 [240614] BOJ 10711 모래성
  seoyoung059/Week_21/BOJ_10711/BOJ_10711.java
  seoyoung059/Week_21/BOJ_10711/BOJ_10711.md
Labels: BFS

#584 [240614] BOJ 10711 모래성
  trankill1127/w21/BOJ_10711.java
Labels: BFS

#583 [240614] BOJ 10711 모래성
  hyunseok0314/Week_21/BOJ_10711_모래성.cpp
Labels: BFS

#566 [240612] BOJ 1661 다솜이의 신발가게
  wnso-kim/Week_21/BOJ_1661_다솜이의신발가게/BOJ_1661_다솜이의신발가게.java
Labels: 도전중

#585 [240614] BOJ 10711 모래성
  yunva17/Week_21/BOJ_10711_모래성/BOJ_10711_모래성.java
Labels: BFS

#588 [240617] BOJ 22255 호석사우루스
  ys4512558/Week_22/BOJ_22255_호석사우르스/BOJ_22255_호석사우르스.java
  ys4512558/Week_22/BOJ_22255_호석사우르스/BOJ_22255_호석사우르스.md
  ys4512558/Week_22/BOJ_22255_호석사우르스/BOJ_22255_호석사우르스_1.png
  ys4512558/Week_22/BOJ_22255_호석사우르스/BOJ_22255_호석사우르스_2.png
  ys4512558/Week_22/BOJ_22255_호석사우르스/BOJ_22255_호석사우르스_3.png
Labels: 다익스트라

#590 [240617] BOJ 22255 호석사우르스
  trankill1127/w22/BOJ_22255.java
Labels: 다익스트라

#593 [240617] BOJ 22255 호석사우루스
  anoldstory/Week_22/BOJ_22255_호석사우르스.cpp
Labels: 다익스트라

#595 [240617] BOJ 22255 호석사우루스
  wnso-kim/Week_22/BOJ_22255_호석사우르스/BOJ_22255_호석사우르스.java
  wnso-kim/Week_22/BOJ_22255_호석사우르스/BOJ_22255_호석사우르스.md
Labels: 다익스트라

#618 [240619] BOJ 30805 사전 순 최대 공통 부분 수열
  anoldstory/Week_22/BOJ_30805_사전순최대공통부분수열.cpp
Labels: 구현

#613 [240619] BOJ 30805 사전 순 최대 공통 부분 수열
  sickbirdd/Week_22/BOJ_30805_사전 순 최대 공통 부분 수열.cpp
  sickbirdd/Week_22/BOJ_30805_사전 순 최대 공통 부분 수열.md
Labels: 그리디 알고리즘

#621 [240619] BOJ 30805 사전 순 최대 공통 부분 수열
  l-umi/Week_22/BOJ_30805_사전_순_최대_공통_부분_수열.py
Labels: 완전 탐색

#634 [240621] BOJ 14722 우유 도시
  sickbirdd/Week_22/BOJ_14722_우유 도시.cpp
  sickbirdd/Week_22/BOJ_14722_우유 도시.md
Labels: DP

#639 [240621] BOJ 14722 우유 도시
  l-umi/Week_22/BOJ_14722_우유_도시.py
Labels: DP

#650 [240624] BOJ 2179 비슷한 단어
  yunva17/Week_23/BOJ_2179_비슷한단어/BOJ_2179_비슷한단어.js
Labels: 도전중

#653 [240626] BOJ 2515 전시장
  hyunseok0314/Week_23/BOJ_2515_전시장.cpp
Labels: DP

#654 [240626] BOJ 2515 전시장
  trankill1127/w23/BOJ_2515.java
Labels: DP

#655 [240626] BOJ 2515 전시장
  ys4512558/Week_23/BOJ_2515_전시장/BOJ_2515_전시장.java
  ys4512558/Week_23/BOJ_2515_전시장/BOJ_2515_전시장.md
Labels: DP, 정렬, 이분 탐색

#656 [24062] BOJ 2515 전시장
  u1qns/Week_23/BOJ_전시장.cpp
Labels: 도전중

#660 [240626] BOJ 2515 전시장
  seoyoung059/Week_23/BOJ_2515/BOJ_2515.java
  seoyoung059/Week_23/BOJ_2515/BOJ_2515.md
Labels: DP, 이분 탐색

#659 [240626] BOJ 2515 전시장
  violetadieu/Week_23/BOJ_2515_전시장.py
Labels: DP

#645 [240624] BOJ 2179 비슷한 단어
  ezeun/Week_23/BOJ_2179_비슷한단어/BOJ_2179_비슷한단어.cpp
  ezeun/Week_23/BOJ_2179_비슷한단어/BOJ_2179_비슷한단어.md
Labels: 정렬

#649 [240624] BOJ 2179 비슷한 단어
  sjhlko/week23/BOJ_2179/BOJ_2179_비슷한단어_성공.java
  sjhlko/week23/BOJ_2515/BOJ_2515_전시장.java
Labels: 구현

#658 [240626] BOJ 2515 전시장
  wnso-kim/Week_23/BOJ_2515_전시장/BOJ_2515_전시장.java
  wnso-kim/Week_23/BOJ_2515_전시장/BOJ_2515_전시장.md
Labels: DP

#664 [240628] BOJ 22866 탑 보기
  hyunseok0314/Week_23/BOJ_22866_탑_보기.cpp
Labels: 스택

#663 [240628] BOJ 22866 탑 보기
  ys4512558/Week_23/BOJ_22866_탑보기/BOJ_22866_탑보기.java
  ys4512558/Week_23/BOJ_22866_탑보기/BOJ_22866_탑보기.md
Labels: 구현, DP, 정렬

#665 [240628] BOJ 22866 탑 보기
  l-umi/Week_23/BOJ_22866_탑_보기.py
Labels: 재귀

#662 [240628] BOJ 22866 탑 보기
  seoyoung059/Week_23/BOJ_22866/BOJ_22866.java
  seoyoung059/Week_23/BOJ_22866/BOJ_22866.md
Labels: 스택

#666 [240628] BOJ 22866 탑 보기
  wnso-kim/Week_23/BOJ_22866_탑보기/BOJ_22866_탑보기.java
  wnso-kim/Week_23/BOJ_22866_탑보기/BOJ_22866_탑보기.md
Labels: DP
