Repository BE-Archive/Algorithm-Study, pull requests merged in 2024-01, with the labels that each got.

#1 [240122] BOJ 2839 설탕 배달 - 1문제
  u1qns/Week_01/BOJ_2839_설탕 배달.cpp
Labels: 그리디 알고리즘

#2 [240122] BOJ 2839 설탕배달 - 1문제
  seoyoung059/Week_01/BOJ_2839.java
Labels: 그리디 알고리즘, DP

#4 [240122] BOJ 설탕 배달 - 1문제
  sickbirdd/Week_01/BOJ_2839_설탕 배달 풀이.java
Labels: DP

#5 [240122] BOJ 2839 설탕배달 - 1문제
  ys4512558/Week_01/BOJ_2839_설탕 배달.java
Labels: DP

#6 [240122] BOJ 2839 설탕 배달
  trankill1127/w01/BOJ_2839.java
Labels: DP

#7 [240122] BOJ 2839 설탕 배달
  wnso-kim/Week_01/BOJ_2839_설탕 배달.md
Labels: 그리디 알고리즘

#10 [240123] BOJ 14719 빗물 - 1문제
  seoyoung059/Week_01/BOJ_14719.java
Labels: 구현, 시뮬레이션

#12 [240123] BOJ 14719 빗물
  trankill1127/w01/BOJ_14719.java
Labels: 구현

#13 [240123] BOJ 14719 빗물
  wnso-kim/Week_01/BOJ_14719_빗물.md
Labels: DP

#14 [240123] BOJ 14719 빗물 - 1문제 구현
  ys4512558/Week_02/BOJ_14719_빗물.java
Labels: 구현

#16 [240123] BOJ 14719 빗물 - 1문제 구현 구현
  ys4512558/Week_01/BOJ_14719_빗물.java
Labels: 구현

#19 [240124] BOJ 4485 녹색 옷 입은 애가 젤다지? - 1문제
  sickbirdd/Week_01/BOJ_4485_녹색 옷 입은 애가 젤다지 풀이.java
Labels: 다익스트라

#20 [240124] BOJ 4485 녹색 옷 입은 애가 젤다지? - 1문제
  ys4512558/Week_01/BOJ_4485_녹색 옷 입은 애가 젤다지.java
Labels: 다익스트라

#22 [240124] BOJ 4485 녹색 옷 입은 애가 젤다지? - 1문제
  seoyoung059/Week_01/BOJ_4485.java
Labels: 다익스트라

#23 [240124] BOJ 4485 녹색 옷 입은 애가 젤다지?
  wnso-kim/Week_01/BOJ_4485_녹색 옷 입은 애가 젤다지.java
  wnso-kim/Week_01/BOJ_4485_녹색 옷 입은 애가 젤다지.md
Labels: 다익스트라

#33 [240126] BOJ 7576 토마토
  wnso-kim/Week_01/BOJ_7576_토마토.java
  wnso-kim/Week_01/BOJ_7576_토마토.md
Labels: BFS

#37 [240129] BOJ 1967 트리의 지름 - 1문제
  sickbirdd/Week_02/BOJ_1967_트리의 지름 풀이.java
Labels: DFS

#38 [240129] BOJ 1967 트리의 지름 - 1문제
  wnso-kim/Week_02/BOJ_1967_트리의 지름.java
  wnso-kim/Week_02/BOJ_1967_트리의 지름.md
Labels: DFS
