Repository BE-Archive/Algorithm-Study, pull requests merged in 2024-02, with the labels that each got.

#102 [240208] BOJ 2750 수 정렬하기(삽입/선택 정렬), BOJ 2751 수 정렬하기 2(병합 정렬)
  wnso-kim/Week_03/BOJ_2750_수정렬하기_삽입_선택/BOJ_2750_수정렬하기_삽입정렬.java
  wnso-kim/Week_03/BOJ_2750_수정렬하기_삽입_선택/BOJ_2750_수정렬하기_삽입정렬.md
  wnso-kim/Week_03/BOJ_2750_수정렬하기_삽입_선택/BOJ_2750_수정렬하기_선택정렬.java
  wnso-kim/Week_03/BOJ_2750_수정렬하기_삽입_선택/BOJ_2750_수정렬하기_선택정렬.md
  wnso-kim/Week_03/BOJ_2751_수정렬하기2_병합정렬/BOJ_2751_수정렬하기2_병합정렬.java
  wnso-kim/Week_03/BOJ_2751_수정렬하기2_병합정렬/BOJ_2751_수정렬하기2_병합정렬.md
Labels: 구현

#127 [240216] BOJ 14940 쉬운 최단거리
  wnso-kim/Week_04/BOJ_14940_쉬운최단거리/BOJ_14940_쉬운최단거리.java
  wnso-kim/Week_04/BOJ_14940_쉬운최단거리/BOJ_14940_쉬운최단거리.md
Labels: BFS

#135 [240219] BOJ 2632 피자판매
  sjhlko/week5/BOJ_2632/BOJ_2632_서정희.java
  sjhlko/week5/BOJ_2632/BOJ_2632_서정희.md
Labels: 누적합

#136 [240219] BOJ 2632 피자판매
  wnso-kim/Week_05/BOJ_2632_피자판매/BOJ_2632_피자판매.java
  wnso-kim/Week_05/BOJ_2632_피자판매/BOJ_2632_피자판매.md
Labels: 누적합

#140 [240220] BOJ 2467 용액
  BOJ_2467_용액.java
  u1qns/Week_05/BOJ_2467_용액.java
Labels: 투포인터

#141 [240220] BOJ 2467 용액
  ys4512558/Week_05/BOJ_2467_용액/BOJ_2467_용액.java
  ys4512558/Week_05/BOJ_2467_용액/BOJ_2467_용액.md
  ys4512558/Week_05/BOJ_2467_용액/BOJ_2467_용액.png
Labels: 이진탐색

#142 [240220] BOJ 2467 용액
  sickbirdd/Week_05/BOJ_2467_용액.java
  sickbirdd/Week_05/BOJ_2467_용액.md
Labels: 투포인터

#143 [240219] BOJ 2632 피자판매
  u1qns/Week_05/BOJ_2632_피자판매.java
Labels: 누적합, 조합

#144 [240221] BOJ 1043 거짓말
  sickbirdd/Week_05/BOJ_1043_거짓말.java
  sickbirdd/Week_05/BOJ_1043_거짓말.md
Labels: 구현

#145 [240221] BOJ 1043 거짓말
  seoyoung059/Week_05/BOJ_1043/BOJ_1043.java
  seoyoung059/Week_05/BOJ_1043/BOJ_1043.md
Labels: 유니온 파인드

#146 [240221] BOJ 1043 거짓말
  sjhlko/week5/BOJ_1043/BOJ_1043_거짓말.java
  sjhlko/week5/BOJ_1043/BOJ_1043_거짓말.md
Labels: 유니온 파인드

#147 [240221] BOJ 1043 거짓말
  u1qns/Week_05/BOJ_1043_거짓말.java
Labels: 유니온 파인드

#149 [240221] BOJ 1043 거짓말
  trankill1127/w05/BOJ_1043.java
Labels: 유니온 파인드

#150 [240221] BOJ 1043 거짓말
  wnso-kim/Week_05/BOJ_1043_거짓말/BOJ_1043_거짓말.java
  wnso-kim/Week_05/BOJ_1043_거짓말/BOJ_1043_거짓말.md
Labels: 유니온 파인드

#155 [240223] BOJ 19238 스타트택시
  ys4512558/Week_05/BOJ19238_스타트택시/BOJ_19238_스타트택시.java
  ys4512558/Week_05/BOJ19238_스타트택시/BOJ_19238_스타트택시.md
Labels: BFS, 구현

#156 [240223] BOJ 19238 스타트택시
  sjhlko/week5/BOJ_19238/BOJ_19238_스타트택시.java
  sjhlko/week5/BOJ_19238/BOJ_19238_스타트택시.md
Labels: BFS, 구현

#157 [240223] BOJ 19238 스타트택시
  u1qns/Week_05/BOJ_19238_스타트택시.cpp
Labels: BFS, 구현

#158 [240223] BOJ 19238 스타트택시
  wnso-kim/Week_05/BOJ_19238_스타트택시/BOJ_19238_스타트택시.java
  wnso-kim/Week_05/BOJ_19238_스타트택시/BOJ_19238_스타트택시.md
Labels: BFS, 구현

#159 [240223] BOJ 19238 스타트택시 - (해결 완료)
  ys4512558/Week_05/BOJ19238_스타트택시/BOJ_19238_스타트택시.java
  ys4512558/Week_05/BOJ19238_스타트택시/BOJ_19238_스타트택시.md
  ys4512558/Week_05/BOJ19238_스타트택시/BOJ_19238_스타트택시_Fail.java
  ys4512558/Week_05/BOJ19238_스타트택시/BOJ_19238_스타트택시_Fail.md
Labels: BFS, 구현
