Repository BE-Archive/Algorithm-Study, pull requests merged in 2024-11, with the labels that each got.

#988 [241104] BOJ 1092 배
  u1qns/Week_42/BOJ_1092.cpp
Labels: 도전중

#987 [241104] BOJ 1092 배
  wnso-kim/Week_42/BOJ_1092_배/BOJ_1092_배.java
  wnso-kim/Week_42/BOJ_1092_배/BOJ_1092_배.md
Labels: 도전중

#994 [241106] BOJ 13913 숨바꼭질 4
  ys4512558/Week_42/BOJ_13913_숨바꼭질4/BOJ_13913_숨바꼭질4.java
  ys4512558/Week_42/BOJ_13913_숨바꼭질4/BOJ_13913_숨바꼭질4.md
Labels: BFS

#991 [241106] BOJ 13913 숨바꼭질 4
  u1qns/Week_42/BOJ_13913_숨바꼭질 4.cpp
Labels: BFS

#992 [241106] BOJ 13913 숨바꼭질 4
  seoyoung059/Week_42/BOJ_13913/BOJ_13913.java
  seoyoung059/Week_42/BOJ_13913/BOJ_13913.md
Labels: BFS

#996 [241106] BOJ 13913 숨바꼭질 4
  l-umi/Week_42/BOJ_13913_숨바꼭질_4.c
  l-umi/Week_42/BOJ_13913_숨바꼭질_4.kt
  l-umi/Week_42/BOJ_13913_숨바꼭질_4.py
Labels: BFS

#993 [241106] BOJ 13913 숨바꼭질 4
  yunva17/Week_42/BOJ_13913_숨바꼭질4/BOJ_13913_숨바꼭질4.js
Labels: BFS

#995 [241106] BOJ 13913 숨바꼭질 4
  wnso-kim/Week_42/BOJ_13913_숨바꼭질_4/BOJ_13913_숨바꼭질_4.java
  wnso-kim/Week_42/BOJ_13913_숨바꼭질_4/BOJ_13913_숨바꼭질_4.md
Labels: BFS

#981 [241104] BOJ 1092 배
  ezeun/Week_42/BOJ_1092_배/BOJ_1092_배.cpp
  ezeun/Week_42/BOJ_1092_배/BOJ_1092_배.md
Labels: 그리디 알고리즘

#986 [241104] BOJ 1092 배
  trankill1127/w42/BOJ_1092.java
Labels: 도전중

#998 [241108] BOJ 1051 숫자 정사각형
  trankill1127/w42/BOJ_1051.java
Labels: 구현

#1004 [241111] BOJ 1072 게임
  trankill1127/w43/BOJ_1072.java
Labels: 이분 탐색

#1009 [241113] BOJ 1166 선물
  yunva17/Week_43/BOJ_1166_선물/BOJ_1166_선물.js
Labels: 이분 탐색

#1015 [241120] BOJ 2138 전구와 스위치
  ezeun/Week_44/BOJ_2138_전구와스위치/BOJ_2138_전구와스위치.java
  ezeun/Week_44/BOJ_2138_전구와스위치/BOJ_2138_전구와스위치.md
Labels: 도전중

#1016 [241122] BOJ 1283 단축키 지정
  ys4512558/Week_44/BOJ_1283_단축키지정/BOJ_1283_단축키지정.java
  ys4512558/Week_44/BOJ_1283_단축키지정/BOJ_1283_단축키지정.md
Labels: 구현

#1026 [241125] BOJ 트리의 순회
  l-umi/Week_45/BOJ_2263_트리의_순회.java
Labels: 재귀

#1023 [241125] BOJ 2263 트리의 순회
  ys4512558/Week_45/BOJ_2263_트리의순회/BOJ_2263_트리의순회.java
  ys4512558/Week_45/BOJ_2263_트리의순회/BOJ_2263_트리의순회.md
  ys4512558/Week_45/BOJ_2263_트리의순회/BOJ_2263_트리의순회_Fail.java
Labels: 재귀
