Repository BE-Archive/Algorithm-Study, pull requests merged in 2024-03, with the labels that each got.

#163 [240228] SWEA 2383 점심 식사시간
  seoyoung059/Week_06/SWEA_2383/SWEA_2383.java
  seoyoung059/Week_06/SWEA_2383/SWEA_2383.md
Labels: 구현, 완전 탐색

#168 [240228] SWEA 2383 점심 식사시간
  wnso-kim/Week_05/BOJ_19238_스타트택시/BOJ_19238_스타트택시.md
  wnso-kim/Week_06/SWEA_2383_점심식사시간/SWEA_2383_점심식사시간.java
  wnso-kim/Week_06/SWEA_2383_점심식사시간/SWEA_2383_점심식사시간.md
Labels: 시뮬레이션

#173 [240301] BOJ_1931_회의실배정
  violetadieu/Week_05/BOJ_1931_회의실배정/BOJ_1931_회의실배정.py
  violetadieu/Week_05/BOJ_2632_피자판매/BOJ_2632_피자판매.py
Labels: 그리디 알고리즘

#176 [240301] BOJ 1931 회의실 배정
  sickbirdd/Week_06/BOJ_1931_회의실 배정.java
  sickbirdd/Week_06/BOJ_1931_회의실 배정.md
Labels: 그리디 알고리즘

#178 [240301] BOJ 1931 회의실 배정
  wnso-kim/Week_06/BOJ_1931_회의실배정/BOJ_1931_회의실배정.java
  wnso-kim/Week_06/BOJ_1931_회의실배정/BOJ_1931_회의실배정.md
Labels: 그리디 알고리즘

#179 [240301] BOJ 1931 회의실 배정
  ys4512558/Week_06/BOJ_1931_회의실배정/BOJ_1931_회의실배정.java
  ys4512558/Week_06/BOJ_1931_회의실배정/BOJ_1931_회의실배정.md
  ys4512558/Week_06/BOJ_1931_회의실배정/BOJ_1931_회의실배정.png
Labels: 그리디 알고리즘

#180 [240301] BOJ 1931 회의실 배정
  sjhlko/week6/BOJ_1931/BOJ_1931_회의실배정.java
  sjhlko/week6/BOJ_1931/BOJ_1931_회의실배정.md
Labels: 그리디 알고리즘

#183 [240301] BOJ 1931 회의실 배정
  seoyoung059/Week_06/BOJ_1931/BOJ_1931.java
  seoyoung059/Week_06/BOJ_1931/BOJ_1931.md
Labels: 그리디 알고리즘

#181 [240301] BOJ 1931 회의실 배정
  trankill1127/w06/BOJ_1931.java
Labels: 그리디 알고리즘

#174 [240301] BOJ 1931 회의실 배정
  u1qns/Week_06/BOJ_1931_회의실 배정.cpp
Labels: 그리디 알고리즘

#184 [240228] BOJ 17472 다리만들기2
  sjhlko/week6/BOJ_17472/BOJ_17472_다리만들기2.java
  sjhlko/week6/BOJ_17472/BOJ_17472_다리만들기2.md
Labels: BFS, 구현, 유니온 파인드

#185 [240228] BOJ 17472 다리만들기2
  u1qns/Week_06/BOJ_17472_다리만들기2,cpp
  u1qns/Week_07/BOJ_내일 할거야.java
Labels: BFS, 유니온 파인드

#195 [240305] BOJ 내일 할거야
  u1qns/Week_07/BOJ_내일 할거야.java
Labels: 그리디 알고리즘

#194 [240306] BOJ 1238 파티
  trankill1127/w07/BOJ_1238.java
Labels: 다익스트라

#190 [240306] BOJ 1238 파티
  ys4512558/Week_07/BOJ_1238_파티/BOJ_1238_파티.java
  ys4512558/Week_07/BOJ_1238_파티/BOJ_1238_파티.md
  ys4512558/Week_07/BOJ_1238_파티/BOJ_1238_파티_1.png
  ys4512558/Week_07/BOJ_1238_파티/BOJ_1238_파티_2.png
Labels: 다익스트라

#193 [240306] BOJ 1238 파티
  sickbirdd/Week_07/BOJ_1238_파티.java
  sickbirdd/Week_07/BOJ_1238_파티.md
Labels: 다익스트라

#196 [240306] BOJ 1238 파티
  u1qns/Week_07/BOJ_1238_파티.java
Labels: 플루이드와샬

#197 [240306] BOJ 1238 파티
  wnso-kim/Week_07/BOJ_1238_파티/BOJ_1238_파티.java
  wnso-kim/Week_07/BOJ_1238_파티/BOJ_1238_파티.md
Labels: 다익스트라

#200 [240307] BOJ 17779 게리맨더링 2
  sickbirdd/Week_07/BOJ_17779_게리맨더링 2.java
  sickbirdd/Week_07/BOJ_17779_게리맨더링 2.md
Labels: BFS, 완전 탐색

#204 [240308]BOJ_2623_음악프로그램
  violetadieu/Week_07/BOJ_2623_음악프로그램/BOJ_2623_음악프로그램.md
  violetadieu/Week_07/BOJ_2623_음악프로그램/BOJ_2623_음악프로그램.py
Labels: 위상 정렬

#208 [240308] BOJ 2623 음악프로그램
  seoyoung059/Week_07/BOJ_2623/BOJ_2623.java
  seoyoung059/Week_07/BOJ_2623/BOJ_2623.md
Labels: 위상 정렬

#207 [240308] BOJ 2623 음악프로그램
  ys4512558/Week_07/BOJ_2623_음악프로그램/BOJ_2623_음악프로그램.java
  ys4512558/Week_07/BOJ_2623_음악프로그램/BOJ_2623_음악프로그램.md
Labels: 위상 정렬

#222 [240313] BOJ 14500 테트로미노
  trankill1127/w08/BOJ_14500.java
Labels: 완전 탐색

#223 [240311] BOJ 1522 문자열 교환
  wnso-kim/Week_08/BOJ_1522_문자열교환/BOJ_1522_문자열교환.java
  wnso-kim/Week_08/BOJ_1522_문자열교환/BOJ_1522_문자열교환.md
Labels: DP

#224 [240313] BOJ 14500 테트로미노
  ys4512558/Week_08/BOJ_14500_테트로미노/BOJ_14500_테트로미노.java
  ys4512558/Week_08/BOJ_14500_테트로미노/BOJ_14500_테트로미노.md
  ys4512558/Week_08/BOJ_14500_테트로미노/BOJ_14500_테트로미노.png
Labels: 구현, 완전 탐색

#225 [240313]BOJ 14500 테트로미노
  violetadieu/Week_08/BOJ_14500_테트로미노/BOJ_14500_테트로미노.py
Labels: DFS, 구현

#226 [240313] BOJ 14500 테트로미노
  sickbirdd/Week_08/BOJ_14500_테트로미노.java
  sickbirdd/Week_08/BOJ_14500_테트로미노.md
Labels: 구현, 완전 탐색

#227 [240313] BOJ 14500 테트로미노
  seoyoung059/Week_08/BOJ_14500/BOJ_14500.java
  seoyoung059/Week_08/BOJ_14500/BOJ_14500.md
Labels: 구현

#228 [240313] BOJ 14500 테트로미노
  sjhlko/week8/BOJ_14500/BOJ_14500_테트로미노.java
  sjhlko/week8/BOJ_14500/BOJ_14500_테트로미노.md
Labels: DFS, 구현

#230 [240313] BOJ 14500 테트로미노
  wnso-kim/Week_08/BOJ_14500_테트로미노/BOJ_14500_테트로미노.java
  wnso-kim/Week_08/BOJ_14500_테트로미노/BOJ_14500_테트로미노.md
Labels: 구현, 완전 탐색

#237 [240314] BOJ 11055 가장 큰 증가하는 부분 수열
  u1qns/Week_08/BOJ_11055_가장 큰 증가하는 부분 수열.java
Labels: DP

#231 [240314] BOJ 11055 가장 큰 증가하는 부분 수열
  seoyoung059/Week_08/BOJ_11055/BOJ_11055.java
  seoyoung059/Week_08/BOJ_11055/BOJ_11055.md
Labels: DP

#233 [240314] BOJ 11055 가장 큰 증가하는 부분 수열
  wnso-kim/Week_08/BOJ_11055_가장큰증가하는부분수열/BOJ_11055_가장큰증가하는부분수열.java
  wnso-kim/Week_08/BOJ_11055_가장큰증가하는부분수열/BOJ_11055_가장큰증가하는부분수열.md
Labels: DP

#234 [240314] BOJ 11055 가장 큰 증가하는 부분 수열
  sickbirdd/Week_08/BOJ_11055_가장 큰 증가하는 부분 수열.java
  sickbirdd/Week_08/BOJ_11055_가장 큰 증가하는 부분 수열.md
Labels: DP

#232 [240314] BOJ 11055 가장 큰 증가하는 부분 수열
  ys4512558/Week_08/BOJ_11055_가장큰증가하는부분수열/BOJ_11055_가장큰증가하는부분수열.java
  ys4512558/Week_08/BOJ_11055_가장큰증가하는부분수열/BOJ_11055_가장큰증가하는부분수열.md
  ys4512558/Week_08/BOJ_11055_가장큰증가하는부분수열/BOJ_11055_가장큰증가하는부분수열.png
Labels: DP

#236 [240315] BOJ 11055 가장큰증가하는수열
  violetadieu/Week_08/BOJ_11055_가장큰증가하는부분수열/BOJ_11055_가장큰증가하는부분수열.cpp
  violetadieu/Week_08/BOJ_11055_가장큰증가하는수열.cpp
Labels: DP

#241 [240318] BOJ 5002 도어맨
  trankill1127/w09/BOJ_5002.java
Labels: 구현

#242 [240318] BOJ 5002 도어맨
  seoyoung059/Week_09/BOJ_5002/BOJ_5002.java
  seoyoung059/Week_09/BOJ_5002/BOJ_5002.md
Labels: 구현

#243 [240318] BOJ 5002 도어맨
  sickbirdd/Week_09/BOJ_5002_도어맨.java
  sickbirdd/Week_09/BOJ_5002_도어맨.md
Labels: 구현

#244 [240318]BOJ 5002 도어맨
  violetadieu/Week_09/BOJ_5002_도어맨.py
Labels: 구현

#245 [240318] BOJ 5002 도어맨
  u1qns/Week_09/BOJ_5002_도어맨.java
Labels: 구현

#248 [240319] BOJ 1916 최소비용 구하기
  u1qns/Week_09/BOJ_1916_최소비용 구하기.java
Labels: 다익스트라

#253 [240331] BOJ 16234 인구 이동
  trankill1127/w09/BOJ_16234.java
Labels: BFS

#252 [240320] BOJ 16234 인구 이동
  sjhlko/week8/BOJ_16234/BOJ_16234_인구이동.java
  sjhlko/week8/BOJ_16234/BOJ_16234_인구이동.md
Labels: 유니온 파인드

#251 [240320] BOJ 16234 인구 이동
  wnso-kim/Week_09/BOJ_16234_인구이동/BOJ_16234_인구이동.java
  wnso-kim/Week_09/BOJ_16234_인구이동/BOJ_16234_인구이동.md
Labels: BFS

#250 [240320] BOJ 16234 인구 이동
  sickbirdd/Week_09/BOJ_16234_인구 이동.java
  sickbirdd/Week_09/BOJ_16234_인구 이동.md
Labels: BFS, 시뮬레이션

#249 [240320] BOJ 16234 인구이동
  seoyoung059/Week_09/BOJ_16234/BOJ_16234.java
  seoyoung059/Week_09/BOJ_16234/BOJ_16234.md
Labels: BFS, 시뮬레이션

#254 [240320] BOJ 16234 인구이동
  ys4512558/Week_09/BOJ_16234_인구이동/BOJ_16234_인구이동.java
  ys4512558/Week_09/BOJ_16234_인구이동/BOJ_16234_인구이동.md
  ys4512558/Week_09/BOJ_16234_인구이동/BOJ_16234_인구이동.png
Labels: 구현
