Repository BE-Archive/Algorithm-Study, pull requests merged in 2024-10, with the labels that each got.

#871 [240930] BOJ 2251 물통
  ys4512558/Week_37/BOJ_2251_물통/BOJ_2251_물통.java
  ys4512558/Week_37/BOJ_2251_물통/BOJ_2251_물통.md
Labels: BFS

#872 [240930] BOJ 2251 물통
  ezeun/Week_37/BOJ_2251_물통/BOJ_2251_물통.cpp
  ezeun/Week_37/BOJ_2251_물통/BOJ_2251_물통.md
Labels: BFS

#874 [240930] BOJ 2251 물통
  yunva17/Week_37/BOJ_2251_물통/BOJ_2251_물통.js
Labels: 재귀

#875 [240930] BOJ 2251 물통
  wnso-kim/Week_37/BOJ_2251_물통/BOJ_2251_물통.java
  wnso-kim/Week_37/BOJ_2251_물통/BOJ_2251_물통.md
Labels: 재귀

#876 [240930] BOJ 2251 물통
  sjhlko/week37/BOJ_2251/Water.java
Labels: DFS, DP

#878 [240930] BOJ 2251 물통
  seoyoung059/Week_37/BOJ_2251/BOJ_2251.java
  seoyoung059/Week_37/BOJ_2251/BOJ_2251.md
Labels: BFS

#877 [240930] BOJ 2251 물통
  l-umi/Week_37/BOJ_2251_물통.py
Labels: BFS

#884 [241002] BOJ 15989 1, 2, 3 더하기 4
  ys4512558/Week_37/BOJ_15989_123더하기4/BOJ_15989_123더하기4.java
  ys4512558/Week_37/BOJ_15989_123더하기4/BOJ_15989_123더하기4.md
Labels: DP

#881 [241002] BOJ 15989 1, 2, 3 더하기 4
  trankill1127/w37/BOJ_15989.java
Labels: DP

#879 [241002] BOJ 15989 1, 2, 3 더하기 4
  u1qns/Week_37/BOJ_15989.cpp
Labels: DP

#883 [241002] BOJ 15989 1, 2, 3 더하기 4
  seoyoung059/Week_37/BOJ_15989/BOJ_15989.java
  seoyoung059/Week_37/BOJ_15989/BOJ_15989.md
Labels: DP

#882 [241002] BOJ 15989 1, 2, 3 더하기 4
  l-umi/Week_37/BOJ_15989_1,2,3더하기.py
Labels: DP

#886 [241002] BOJ 15989 1, 2, 3 더하기 4
  wnso-kim/Week_37/BOJ_15989_123더하기4/BOJ_15989_123더하기4.java
  wnso-kim/Week_37/BOJ_15989_123더하기4/BOJ_15989_123더하기4.md
Labels: DP

#885 [241002] BOJ 15989 1, 2, 3 더하기 4
  sjhlko/week37/BOJ_15989/LeeHi.java
Labels: DP

#888 [241004] BOJ 13414 수강신청
  ys4512558/Week_37/BOJ_13414_수강신청/BOJ_13414_수강신청.java
  ys4512558/Week_37/BOJ_13414_수강신청/BOJ_13414_수강신청.md
Labels: 자료구조

#889 [241004] BOJ 13414 수강신청
  u1qns/Week_37/BOJ_13414.cpp
Labels: 구현

#890 [241004] BOJ 13414 수강신청
  seoyoung059/Week_37/BOJ_13414/BOJ_13414.java
  seoyoung059/Week_37/BOJ_13414/BOJ_13414.md
Labels: 자료구조, 정렬

#891 [241004] BOJ 13414 수강신청
  trankill1127/w37/BOJ_13414.java
Labels: 자료구조

#893 [241004] BOJ 13414 수강신청
  l-umi/Week_37/BOJ_13414_수강신청.py
Labels: 자료구조

#892 [241004] BOJ 13414 수강신청
  wnso-kim/Week_37/BOJ_13414_수강신청/BOJ_13414_수강신청.java
  wnso-kim/Week_37/BOJ_13414_수강신청/BOJ_13414_수강신청.md
Labels: 자료구조

#894 [241004] BOJ 13414 수강신청
  yunva17/Week_37/BOJ_13414_수강신청/BOJ_13414_수강신청.js
Labels: 자료구조

#902 [241007] BOJ 17845 수강 과목
  ys4512558/Week_38/BOJ_17845_수강과목/BOJ_17845_수강과목.java
  ys4512558/Week_38/BOJ_17845_수강과목/BOJ_17845_수강과목.md
Labels: DP

#901 [241007] BOJ 17845 수강 과목
  l-umi/Week_38/BOJ_17845_수강_과목.py
Labels: DP

#906 [241007] BOJ 17845 수강 과목
  wnso-kim/Week_38/BOJ_17845_수강_과목/BOJ_17845_수강_과목.java
  wnso-kim/Week_38/BOJ_17845_수강_과목/BOJ_17845_수강_과목.md
Labels: DP

#907 [241007] BOJ 17845 수강 과목
  yunva17/Week_38/BOJ_17845_수강과목/BOJ_17845_수강과목.js
Labels: DP

#916 [241009] BOJ 1063 킹
  wnso-kim/Week_38/BOJ_1063_킹/BOJ_1063_킹.java
  wnso-kim/Week_38/BOJ_1063_킹/BOJ_1063_킹.md
Labels: 구현, 시뮬레이션

#913 [241009] BOJ 1063 킹
  trankill1127/w38/BOJ_1063.java
Labels: 구현

#922 [241014] BOJ 2533 사회망 서비스(SNS)
  ys4512558/Week_39/BOJ_2533_사회망서비스SNS/BOJ_2533_사회망서비스SNS.java
  ys4512558/Week_39/BOJ_2533_사회망서비스SNS/BOJ_2533_사회망서비스SNS.md
Labels: DP

#920 [241009] BOJ 2533 사회망 서비스(SNS)
  l-umi/Week_39/BOJ_2533_사회망_서비스.py
Labels: 그리디 알고리즘, 재귀

#921 [241014] BOJ 2533 사회망 서비스(SNS)
  trankill1127/w37/BOJ_2533.java
Labels: DP

#924 [241016] BOJ 9996 한국이 그리울 땐 서버에 접속하지
  u1qns/Week_39/BOJ_9996.cpp
Labels: 문자열

#928 [241016] BOJ 9996 한국이 그리울 땐 서버에 접속하지
  trankill1127/w39/BOJ_9996.java
Labels: 문자열

#929 [241016] BOJ 9996 한국이 그리울 땐 서버에 접속하지
  wnso-kim/Week_39/BOJ_9996_한국이_그리울_땐_서버에_접속하지.java
  wnso-kim/Week_39/BOJ_9996_한국이_그리울_땐_서버에_접속하지.md
Labels: 문자열

#930 [241016] BOJ 9996 한국이 그리울 땐 서버에 접속하지
  l-umi/Week_39/BOJ_9996_한국이_그리울_땐_서버에_접속하지.py
Labels: 그리디 알고리즘

#931 [241016] BOJ 9996 한국이 그리울 땐 서버에 접속하지
  sjhlko/week39/BOJ_9996/ServerOn.java
Labels: 문자열

#925 [241016] BOJ 9996 한국이 그리울 땐 서버에 접속하지
  yunva17/Week_39/BOJ_9996_한국이그리울땐서버에접속하지/BOJ_9996_한국이그리울땐서버에접속하지.js
Labels: 문자열

#927 [241016] BOJ 9996 한국이 그리울 땐 서버에 접속하지
  seoyoung059/Week_39/BOJ_9996/BOJ_9996.java
  seoyoung059/Week_39/BOJ_9996/BOJ_9996.md
Labels: 문자열

#937 [241018] BOJ 1188 음식 평론가
  u1qns/Week_39/BOJ_1188.cpp
Labels: 수학

#936 [241018] BOJ 1188 음식 평론가
  seoyoung059/Week_39/BOJ_1188/BOJ_1188.java
  seoyoung059/Week_39/BOJ_1188/BOJ_1188.md
Labels: 수학

#932 [241018] BOJ 1188 음식 평론가
  wnso-kim/Week_39/BOJ_1188_음식_평론가/BOJ_1188_음식_평론가.java
  wnso-kim/Week_39/BOJ_1188_음식_평론가/BOJ_1188_음식_평론가.md
  wnso-kim/Week_39/BOJ_9996_한국이_그리울_땐_서버에_접속하지/BOJ_9996_한국이_그리울_땐_서버에_접속하지.java
  wnso-kim/Week_39/BOJ_9996_한국이_그리울_땐_서버에_접속하지/BOJ_9996_한국이_그리울_땐_서버에_접속하지.md
Labels: 수학

#940 [241021] BOJ 17175 피보나치는 지겨웡~
  ys4512558/Week_40/BOJ_17175_피보나치는지겨웡/BOJ_17175_피보나치는지겨웡.java
  ys4512558/Week_40/BOJ_17175_피보나치는지겨웡/BOJ_17175_피보나치는지겨웡.md
Labels: DP

#939 [241021] BOJ 17175 피보나치는 지겨웡~
  ezeun/Week_40/BOJ_17175_피보나치는지겨웡/BOJ_17175_피보나치는지겨웡.cpp
  ezeun/Week_40/BOJ_17175_피보나치는지겨웡/BOJ_17175_피보나치는지겨웡.md
Labels: DP

#941 [241021] BOJ 17175 피보나치는 지겨웡~
  seoyoung059/Week_40/BOJ_17175/BOJ_17175.java
  seoyoung059/Week_40/BOJ_17175/BOJ_17175.md
Labels: DP

#942 [241021] BOJ 17175 피보나치는 지겨웡~
  trankill1127/w40/BOJ_17175.java
Labels: DP

#943 [241021] BOJ 17175 피보나치는 지겨웡~
  yunva17/Week_40/BOJ_17175_피보나치는지겨웡/BOJ_17175_피보나치는지겨웡.js
Labels: DP

#944 [241021] BOJ 17175 피보나치는 지겨웡~
  wnso-kim/Week_40/BOJ_17175_피보나치는_지겨웡/BOJ_17175_피보나치는_지겨웡.java
  wnso-kim/Week_40/BOJ_17175_피보나치는_지겨웡/BOJ_17175_피보나치는_지겨웡.md
Labels: DP

#945 [241021] BOJ 17175 피보나치는 지겨웡~
  l-umi/Week_40/BOJ_17175_피보나치는.py
Labels: DP

#946 [241023] BOJ 1719 택배
  ys4512558/Week_40/BOJ_1719_택배/BOJ_1719_택배.java
  ys4512558/Week_40/BOJ_1719_택배/BOJ_1719_택배.md
Labels: 다익스트라

#947 [241023] BOJ 1719 택배
  u1qns/Week_40/BOJ_1719.cpp
Labels: 다익스트라

#948 [241023] BOJ 1719 택배
  seoyoung059/Week_40/BOJ_1719/BOJ_1719.java
  seoyoung059/Week_40/BOJ_1719/BOj_1719.md
Labels: 플로이드-워셜

#949 [241023] BOJ 1719 택배
  l-umi/Week_40/BOJ_1719_택배.py
Labels: 플로이드-워셜

#950 [241023] BOJ 1719 택배
  wnso-kim/Week_40/BOJ_1719_택배/BOJ_1719_택배.java
  wnso-kim/Week_40/BOJ_1719_택배/BOJ_1719_택배.md
Labels: 플로이드-워셜

#951 [241023] BOJ 1719 택배
  yunva17/Week_40/BOJ_1719_택배/BOJ_1719_택배.js
Labels: 플로이드-워셜

#952 [241023] BOJ 1719 택배
  hyunseok0314/Week_40/BOJ_1719_택배.go
Labels: 플로이드-워셜

#958 [241025] BOJ 1614 영식이의 손가락
  u1qns/Week_40/BOJ_1614.cpp
Labels: 규칙찾기

#956 [241025] BOJ 1614 영식이의 손가락
  ys4512558/Week_40/BOJ_1614_영식이의손가락/BOJ_1614_영식이의손가락.java
  ys4512558/Week_40/BOJ_1614_영식이의손가락/BOJ_1614_영식이의손가락.md
Labels: 수학

#959 [241025] BOJ 1614 영식이의 손가락
  wnso-kim/Week_40/BOJ_1614_영식이의_손가락/BOJ_1614_영식이의_손가락.java
  wnso-kim/Week_40/BOJ_1614_영식이의_손가락/BOJ_1614_영식이의_손가락.md
Labels: 수학, 규칙찾기

#957 [241025] BOJ 1614 영식이의 손가락
  l-umi/Week_40/BOJ_1614_영식이의손가락.kt
Labels: 규칙찾기
