Repository BE-Archive/Algorithm-Study, pull requests merged in 2024-07, with the labels that each got.

#671 [240701] BOJ 17396 백도어
  yunva17/Week_24/BOJ_17396_백도어/BOJ_17396_백도어.java
Labels: 다익스트라

#672 [240701] BOJ 17396 백도어
  sjhlko/week24/BOJ_17396_백도어/BackDoor.java
Labels: 도전중

#668 [240701] BOJ 17396 백도어
  seoyoung059/Week_24/BOJ_17396/BOJ_17396.java
  seoyoung059/Week_24/BOJ_17396/BOJ_17396.md
Labels: 다익스트라

#670 [240701] BOJ 17396 백도어
  ys4512558/Week_24/BOJ_17396_백도어.java
  ys4512558/Week_24/BOJ_17396_백도어.md
Labels: 다익스트라

#673 [240701] BOJ 17396 백도어
  ezeun/Week_24/BOJ_17396_백도어/BOJ_17396_백도어.cpp
  ezeun/Week_24/BOJ_17396_백도어/BOJ_17396_백도어.md
Labels: 다익스트라

#678 [240701] BOJ 17396 백도어
  u1qns/Week_24/BOJ_17396_백도어.cpp
Labels: 다익스트라

#679 [240701] BOJ 17396 백도어
  l-umi/Week_24/BOJ_17396_백도어.py
Labels: 다익스트라

#674 [240701] BOJ 17396 백도어
  sjhlko/week24/BOJ_17396/BOJ_17396_백도어.java
Labels: 다익스트라

#682 [240703] BOJ 1041 주사위
  ys4512558/Week_24/BOJ_1041_주사위/BOJ_1041_주사위.java
  ys4512558/Week_24/BOJ_1041_주사위/BOJ_1041_주사위.md
  ys4512558/Week_24/BOJ_1041_주사위/BOJ_1041_주사위.png
  ys4512558/Week_24/BOJ_17396_백도어/BOJ_17396_백도어.java
  ys4512558/Week_24/BOJ_17396_백도어/BOJ_17396_백도어.md
Labels: 구현

#683 [240703] BOJ 1041 주사위
  ezeun/Week_24/BOJ_1041_주사위/BOJ_1041_주사위.cpp
  ezeun/Week_24/BOJ_1041_주사위/BOJ_1041_주사위.md
Labels: 구현

#684 [240703] BOJ 1041 주사위
  sjhlko/week24/BOJ_1041/BOJ_1041_주사위.java
Labels: 구현

#685 [240703] BOJ 1041 주사위
  seoyoung059/Week_24/BOJ_1041/BOJ_1041.java
  seoyoung059/Week_24/BOJ_1041/BOJ_1041.md
Labels: 그리디 알고리즘, 구현, 조합

#687 [240703] BOJ 1041 주사위
  wnso-kim/Week_24/BOJ_1041_주사위/BOJ_1041_주사위.java
  wnso-kim/Week_24/BOJ_1041_주사위/BOJ_1041_주사위.md
Labels: 구현

#688 [240703] BOJ 1041 주사위
  hyunseok0314/Week_24/BOJ_1041_주사위.cpp
Labels: 수학

#686 [240703] BOJ 1041 주사위
  l-umi/Week_24/BOJ_1041_주사위.py
Labels: 규칙찾기

#689 [240703] BOJ 1041 주사위
  u1qns/Week_24/BOJ_1041_주사위.cpp
Labels: 수학

#690 [240703] BOJ 1041 주사위
  sickbirdd/Week_24/BOJ_1041_주사위.cpp
  sickbirdd/Week_24/BOJ_1041_주사위.md
Labels: 수학

#691 [240704] BOJ 1041 주사위
  trankill1127/w24/BOJ_1041.java
Labels: 수학, 완전 탐색

#693 [240705] BOJ 21606 아침 산책
  ys4512558/Week_24/BOJ_21606_아침산책/BOJ_21606_아침산책.java
  ys4512558/Week_24/BOJ_21606_아침산책/BOJ_21606_아침산책.md
  ys4512558/Week_24/BOJ_21606_아침산책/BOJ_21606_아침산책1.png
  ys4512558/Week_24/BOJ_21606_아침산책/BOJ_21606_아침산책2.png
Labels: 유니온 파인드

#697 [240705] BOJ 21606 아침 산책
  sjhlko/week24/BOJ_21606/BOJ_21606_아침산책.java
Labels: BFS, 구현

#699 [240705] BOJ 21606 아침 산책
  wnso-kim/Week_24/BOJ_21606_아침산책/BOJ_21606_아침산책.java
  wnso-kim/Week_24/BOJ_21606_아침산책/BOJ_21606_아침산책.md
Labels: 유니온 파인드

#700 [240705] BOJ 21606 아침 산책
  hyunseok0314/Week_24/BOJ_21606_아침_산책.cpp
Labels: 유니온 파인드

#696 [240705] BOJ 21606 아침 산책
  u1qns/Week_24/BOJ_21606_아침산책.cpp
Labels: 도전중

#698 [240705] BOJ 21606 아침 산책
  yunva17/Week_24/BOJ_21606_아침산책/BOJ_21606_아침산책.js
Labels: 도전중

#694 [240705] BOJ 21606 아침 산책
  ezeun/Week_24/BOJ_21606_아침산책/BOJ_21606_아침산책.cpp
  ezeun/Week_24/BOJ_21606_아침산책/BOJ_21606_아침산책.md
  ezeun/Week_24/BOJ_21606_아침산책/image.png
Labels: DFS

#701 [240705] BOJ 21606 아침 산책
  seoyoung059/Week_24/BOJ_21606/BOJ_21606.java
  seoyoung059/Week_24/BOJ_21606/BOJ_21606.md
Labels: DFS

#710 [240710] BOJ 2662 기업투자
  u1qns/Week_25/BOJ_2662 _기업투자.cpp
Labels: DP

#721 [240712] BOJ 1600 말이 되고픈 원숭이
  ezeun/Week_25/BOJ_1600_말이되고픈원숭이/BOJ_1600_말이되고픈원숭이.cpp
  ezeun/Week_25/BOJ_1600_말이되고픈원숭이/BOJ_1600_말이되고픈원숭이.md
Labels: 도전중

#725 [240715] BOJ 16432 떡장수와 호랑이
  sjhlko/week26/BOJ_16432/BOJ_16432_떡장수와호랑이.java
Labels: BFS

#726 [240715] BOJ 16432 떡장수와 호랑이
  ys4512558/Week_26/BOJ_16432_떡장수와호랑이/BOJ_16432_떡장수와호랑이.java
  ys4512558/Week_26/BOJ_16432_떡장수와호랑이/BOJ_16432_떡장수와호랑이.md
Labels: DFS, 구현

#727 [240715] BOJ 16432 떡장수와 호랑이
  seoyoung059/Week_26/BOJ_16432/BOJ_16342.md
  seoyoung059/Week_26/BOJ_16432/BOJ_16432.java
Labels: DP

#728 [240715] BOJ 16432 떡장수와 호랑이
  u1qns/Week_26/BOJ_16432_떡장수와 호랑이.cpp
Labels: DFS

#730 [240716] BOJ 16432 떡장수와 호랑이
  wnso-kim/Week_26/BOJ_16432_떡장수와_호랑이/BOJ_16432_떡장수와_호랑이.java
  wnso-kim/Week_26/BOJ_16432_떡장수와_호랑이/BOJ_16432_떡장수와_호랑이.md
Labels: DP

#729 [240716] BOJ 16432 떡장수와 호랑이
  trankill1127/w26/BOJ_16432.java
Labels: DFS

#740 [240719] BOJ 15654 N과 M (5)
  ys4512558/Week_26/BOJ_15654_N과M5/BOJ_15654_N과M5.java
  ys4512558/Week_26/BOJ_15654_N과M5/BOJ_15654_N과M5.md
Labels: 순열

#757 [240722] BOJ 1158 요세푸스 문제
  seoyoung059/BOJ_1158/BOJ_1158.java
  seoyoung059/BOJ_1158/BOJ_1158.md
Labels: 구현

#751 [240722] BOJ 1158 요세푸스 문제
  yunva17/Week_27/BOJ_1158_요세푸스문제/BOJ_1158_요세푸스문제.js
Labels: 구현, 큐

#767 [240726] BOJ 15684 사다리 조작
  hyunseok0314/Week_27/BOJ_15684_사다리_조작.cpp
Labels: DFS

#763 [240725] BOJ 5904 Moo 게임
  trankill1127/w27/BOJ_5904.java
Labels: 도전중

#764 [240724] BOJ 5904 Moo 게임
  u1qns/Week_27/BOJ_5904_Moo게임.cpp
Labels: 도전중

#765 [240724] BOJ 5904 Moo 게임
  sjhlko/week27/BOJ_15684/Ladder.java
  sjhlko/week27/BOJ_5904/MooGame.java
Labels: 도전중

#769 [240726] BOJ 15684 사다리 조작
  yunva17/Week_27/BOJ_15684_사다리조작/BOJ_15684_사다리조작.js
Labels: 도전중

#760 [240724] BOJ 5904 Moo 게임
  seoyoung059/Week_27/BOJ_5904/BOJ_5904.java
  seoyoung059/Week_27/BOJ_5904/BOJ_5904.md
Labels: 재귀

#770 [240726] BOJ 15684 사다리 조작
  l-umi/Week_27/BOJ_15684_사다리_조작.py
Labels: 백트래킹

#773 [240729] BOJ 2470 두 용액
  seoyoung059/Week_28/BOJ_2470/BOJ_2470.java
  seoyoung059/Week_28/BOJ_2470/BOJ_2470.md
Labels: 이분 탐색

#777 [240729] BOJ 2470 두 용액
  wnso-kim/Week_28/BOJ_2470_두_용액/BOJ_2470_두_용액.java
  wnso-kim/Week_28/BOJ_2470_두_용액/BOJ_2470_두_용액.md
Labels: 투포인터
