Repository BE-Archive/Algorithm-Study, pull requests merged in 2024-09, with the labels that each got.

#820 [240902] BOJ 1253 좋다
  yunva17/Week_33/BOJ_1253_좋다/BOJ_1253_좋다.js
Labels: 투포인터

#819 [240902] BOJ 1253 좋다
  l-umi/Week_33/BOJ_1253_좋다.java
Labels: 투포인터

#816 [240902] BOJ 1253 좋다
  trankill1127/w33/BOJ_1253.java
  trankill1127/w33/BOJ_2668.java
Labels: 투포인터, 정렬

#825 [240906] BOJ 1005 ACM Craft
  ys4512558/Week_33/BOJ_1005_ACMCraft/BOJ_1005_ACMCraft.java
  ys4512558/Week_33/BOJ_1005_ACMCraft/BOJ_1005_ACMCraft.md
Labels: DFS, DP

#827 [240906] BOJ 1005 ACM Craft
  seoyoung059/Week_33/BOJ_1005/BOJ_1005.java
  seoyoung059/Week_33/BOJ_1005/BOJ_1005.md
Labels: 위상 정렬

#829 [240906] BOJ 1005 ACM Craft
  sjhlko/week33/BOJ_1005/BOJ_1005.java
Labels: DP

#830 [240906] BOJ 1005 ACM Craft
  l-umi/Week_33/BOJ_1005_ACM_Craft.java
Labels: 위상 정렬

#826 [240906] BOJ 1005 ACM Craft
  wnso-kim/Week_33/BOJ_1005_ACM_Craft/BOJ_1005_ACM_Craft.java
  wnso-kim/Week_33/BOJ_1005_ACM_Craft/BOJ_1005_ACM_Craft.md
Labels: 위상 정렬

#832 [240909] BOJ 11403 경로 찾기
  ys4512558/Week_34/BOJ_11403_경로찾기/BOJ_11403_경로찾기.java
  ys4512558/Week_34/BOJ_11403_경로찾기/BOJ_11403_경로찾기.md
Labels: 플로이드-워셜

#828 [240906] SWEA 병사 관리
  trankill1127/w33/SWEA_병사_관리.java
  trankill1127/w33/SWEA_수열_편집.java
  trankill1127/w33/SWEA_암호문3.java
Labels: 자료구조

#843 [240923] BOJ 28017 게임을 클리어하자
  wnso-kim/Week_36/BOJ_28017_게임을_클리어하자.java
  wnso-kim/Week_36/BOJ_28017_게임을_클리어하자.md
Labels: DP

#861 [240927] BOJ 7511 소셜 네트워킹 어플리케이션
  u1qns/Week_36/BOJ_7511_소셜_네트워킹_어플리케이션.cpp
Labels: 유니온 파인드

#862 [240927] BOJ 7511 소셜 네트워킹 어플리케이션
  trankill1127/w36/BOJ_7511.java
Labels: 유니온 파인드

#863 [240927] BOJ 7511 소셜 네트워킹 어플리케이션
  ezeun/Week_36/BOJ_7511_소셜네트워킹어플리케이션/BOJ_7511_소셜네트워킹어플리케이션.cpp
  ezeun/Week_36/BOJ_7511_소셜네트워킹어플리케이션/BOJ_7511_소셜네트워킹어플리케이션.md
Labels: 유니온 파인드

#869 [240927] BOJ 7511 소셜 네트워킹 어플리케이션
  wnso-kim/Week_36/BOJ_7511_소셜_네트워킹_어플리케이션/BOJ_7511_소셜_네트워킹_어플리케이션.java
  wnso-kim/Week_36/BOJ_7511_소셜_네트워킹_어플리케이션/BOJ_7511_소셜_네트워킹_어플리케이션.md
Labels: 유니온 파인드

#867 [240927] BOJ 7511 소셜 네트워킹 어플리케이션
  l-umi/Week_36/BOJ_7511_소셜_네트워킹_어플리케이션.py
Labels: 유니온 파인드
