Repository BE-Archive/Algorithm-Study, pull requests merged in 2024-05, with the labels that each got.

#379 [240429] BOJ 1516 게임개발
  sjhlko/week15/BOJ_1516_게임개발/BOJ_1516_게임개발.java
  sjhlko/week15/BOJ_1516_게임개발/BOJ_1516_게임개발.md
Labels: 위상 정렬

#381 [240429] BOJ 1516 게임 개발
  ys4512558/Week_15/BOJ_1516_게임개발/BOJ_1516_게임개발.java
  ys4512558/Week_15/BOJ_1516_게임개발/BOJ_1516_게임개발.md
Labels: 위상 정렬

#384 [240429] BOJ 1516 게임 개발
  violetadieu/Week_15/BOJ_1516_게임 개발.py
Labels: 위상 정렬

#385 [240429] BOJ 1516 게임 개발
  u1qns/Week_15/BOJ_1516_게임개발.java
Labels: DFS, DP

#380 [240429] BOJ 1516 게임 개발
  trankill1127/w15/BOJ_1516.java
Labels: BFS, DP, 위상 정렬

#391 [240503] BOJ 1081 합
  ys4512558/Week_15/BOJ_1081_합/BOJ_1081_합.java
  ys4512558/Week_15/BOJ_1081_합/BOJ_1081_합.md
  ys4512558/Week_15/BOJ_1081_합/BOJ_1081_합_1.png
  ys4512558/Week_15/BOJ_1081_합/BOJ_1081_합_2.png
Labels: 구현

#393 [240503] BOJ 1081 합
  u1qns/Week_15/BOJ_1081_합.java
Labels: 도전중

#394 [240503] BOJ 1081 합
  wnso-kim/Week_15/BOJ_1081_합/BOJ_1081_합_실패.java
  wnso-kim/Week_15/BOJ_1081_합/BOJ_1081_합_실패.md
Labels: 도전중

#398 [240508] BOJ 21924 도시 건설
  ys4512558/Week_16/BOJ_21924_도시건설/BOJ_21924_도시건설.java
  ys4512558/Week_16/BOJ_21924_도시건설/BOJ_21924_도시건설.md
Labels: 크루스칼

#402 [240508] BOJ 21924 도시 건설
  trankill1127/w16/BOJ_21924.java
Labels: 프림

#401 [240508] BOJ 21924 도시 건설
  violetadieu/Week_16/BOJ_21924_도시건설.py
Labels: 유니온 파인드, 크루스칼

#404 [240508] BOJ 21924 도시 건설
  wnso-kim/Week_16/BOJ_21924_도시건설/BOJ_21924_도시건설.java
  wnso-kim/Week_16/BOJ_21924_도시건설/BOJ_21924_도시건설.md
Labels: 프림

#399 [240508] BOJ 21924 도시 건설
  yunva17/Week_16/BOJ_21924_도시건설/BOJ_21924_도시건설.java
Labels: 크루스칼

#407 [240510] BOJ 16928 뱀과 사다리 게임
  ys4512558/Week_16/BOJ_16928_뱀과사다리게임/BOJ_16928_뱀과사다리게임.java
  ys4512558/Week_16/BOJ_16928_뱀과사다리게임/BOJ_16928_뱀과사다리게임.md
Labels: BFS

#408 [240510] BOJ 16928 뱀과 사다리 게임
  seoyoung059/Week_16/BOJ_16928/BOJ_16928.java
  seoyoung059/Week_16/BOJ_16928/BOj_16928.md
Labels: BFS

#409 [240510] BOJ 16928 뱀과 사다리 게임
  sjhlko/week16/BOJ_16928/BOJ16928_뱀과사다리게임.java
Labels: BFS

#410 [240510] BOJ 16928 뱀과 사다리 게임
  sickbirdd/Week_16/BOJ_16928_뱀과 사다리 게임.java
  sickbirdd/Week_16/BOJ_16928_뱀과 사다리 게임.md
Labels: BFS

#411 [240510] BOJ 16928 뱀과 사다리 게임
  yunva17/Week_16/BOJ_16928_뱀과사다리게임/BOJ_16928_뱀과사다리게임.java
Labels: BFS

#406 [240510] BOJ 16928 뱀과 사다리 게임
  u1qns/Week_16/BOJ_16928_뱀과사다리게임.java
Labels: BFS

#418 [240513] BOJ 18223 민준이와 마산 그리고 건우
  u1qns/Week_16/BOJ_18223_민준이와 마산 그리고 건우.java
Labels: 다익스트라

#414 [240513] BOJ 18223 민준이와 마산 그리고 건우
  trankill1127/w17/BOJ_18223.java
Labels: 다익스트라

#417 [240513] BOJ 18223 민준이와 마산 그리고 건우
  seoyoung059/Week_17/BOJ_18223/BOJ_18223.java
  seoyoung059/Week_17/BOJ_18223/BOJ_18223.md
Labels: 다익스트라

#419 [240513] BOJ 18223 민준이와 마산 그리고 건우
  violetadieu/Week_17/BOJ_18223_민준이와마산그리고건우
Labels: 다익스트라

#421 [240517] BOJ 2638 치즈
  ys4512558/Week_17/BOJ_2638/BOJ_2638_치즈.java
  ys4512558/Week_17/BOJ_2638/BOJ_2638_치즈.md
Labels: BFS, 시뮬레이션

#423 [240517] BOJ 2638 치즈
  seoyoung059/Week_17/BOJ_2638/BOJ_2638.java
  seoyoung059/Week_17/BOJ_2638/BOJ_2638.md
Labels: BFS

#425 [240517] BOJ 2638 치즈
  sickbirdd/Week_17/BOJ_2638_치즈.java
  sickbirdd/Week_17/BOJ_2638_치즈.md
Labels: BFS

#428 [240518] BOJ 2638 치즈
  trankill1127/w17/BOJ_2638.java
Labels: BFS

#429 [240518] BOJ 2638 치즈
  sjhlko/week17/BOJ2638/BOJ2638_치즈.java
Labels: BFS

#427 [240517] BOJ 2638 치즈
  yunva17/Week_17/BOJ_2638_치즈/BOJ_2638_치즈.java
Labels: BFS

#424 [240517] BOJ 2638 치즈
  violetadieu/Week_17/BOJ_2638_치즈.py
Labels: BFS

#432 [240520] BOJ 17219 비밀번호 찾기
  ys4512558/Week_17/BOJ_2638_치즈/BOJ_2638_치즈.java
  ys4512558/Week_17/BOJ_2638_치즈/BOJ_2638_치즈.md
  ys4512558/Week_18/BOJ_17219_비밀번호찾기/BOJ_17219_비밀번호찾기.java
  ys4512558/Week_18/BOJ_17219_비밀번호찾기/BOJ_17219_비밀번호찾기.md
Labels: 자료구조

#439 [240520] BOJ 17219 비밀번호 찾기
  yunva17/Week_18/BOJ_17219_비밀번호찾기/BOJ_17219_비밀번호찾기.js
Labels: 문자열

#438 [240520] BOJ 17219 비밀번호 찾기
  wnso-kim/Week_18/BOJ_17219_비밀번호찾기/BOJ_17219_비밀번호찾기.java
  wnso-kim/Week_18/BOJ_17219_비밀번호찾기/BOJ_17219_비밀번호찾기.md
Labels: 문자열

#437 [250521] BOJ 17219 비밀번호 찾기
  violetadieu/Week_18/BOJ_17219_비밀번호찾기.py
Labels: 자료구조

#435 [240520] BOJ 17219 비밀번호 찾기
  sjhlko/week18/BOJ_17219_비밀번호찾기.java
Labels: 자료구조

#434 [240520] BOJ 17219 비밀번호 찾기
  sickbirdd/Week_18/BOJ_17219_비밀번호 찾기.java
  sickbirdd/Week_18/BOJ_17219_비밀번호 찾기.md
Labels: 구현

#433 [240520] BOJ 17219 비밀번호 찾기
  seoyoung059/Week_18/BOJ_17219/BOJ_17219.java
  seoyoung059/Week_18/BOJ_17219/BOJ_17219.md
Labels: 자료구조

#436 [250521] BOJ 17219 비밀번호 찾기
  trankill1127/w18/BOJ_17219.java
Labels: 자료구조

#442 [240522] BOJ 1389 케빈 베이컨의 6단계 법칙
  sickbirdd/Week_18/BOJ_1389_케빈 베이컨의 6단계 법칙.java
  sickbirdd/Week_18/BOJ_1389_케빈 베이컨의 6단계 법칙.md
Labels: BFS

#441 [240522] BOJ 1389 케빈 베이컨의 6단계 법칙
  ys4512558/Week_18/BOJ_1389_케빈베이컨의6단계법칙/BOJ_1389_케빈베이컨의6단계법칙.java
  ys4512558/Week_18/BOJ_1389_케빈베이컨의6단계법칙/BOJ_1389_케빈베이컨의6단계법칙.md
Labels: 플루이드와샬

#452 [240527] BOJ 2448 별찍기-11
  ezeun/Week_19/BOJ_2448_별찍기11/2448.png
  ezeun/Week_19/BOJ_2448_별찍기11/BOJ_2448_별찍기11.cpp
  ezeun/Week_19/BOJ_2448_별찍기11/BOJ_2448_별찍기11.md
Labels: 재귀

#453 [240527] BOJ 2448 별 찍기 - 11
  u1qns/Week_19/BOJ_2448_별찍기11.cpp
Labels: 재귀

#449 [240527] BOJ 2448 별찍기-11
  trankill1127/w19/BOJ_2448.java
Labels: 재귀

#446 [240527] BOJ 2448 별 찍기 - 11
  hyunseok0314/.gitignore
  hyunseok0314/Week_19/BOJ_2448_별_찍기.java
Labels: 구현

#445 [240527] BOJ 2448 별 찍기 - 11
  l-umi/Week_19/BOJ_2448_별찍기.py
Labels: 규칙찾기

#447 [240527] BOJ 2448 별 찍기 - 11
  violetadieu/Week_19/BOJ_2448_별찍기11.py
Labels: 재귀

#456 [240527] BOJ 2448 별찍기-11
  yunva17/Week_19/BOJ_2448_별찍기11/BOJ_2448_별찍기11.js
Labels: 재귀

#457 [240527] BOJ 2448 별 찍기 - 11
  sjhlko/week19/BOJ_2448/BOJ_2448_별찍기11.java
Labels: 구현

#471 [240528] BOJ 14621 나만 안되는 연애
  seoyoung059/Week_19/BOJ_14621/BOJ_14621.java
  seoyoung059/Week_19/BOJ_14621/BOJ_14621.md
Labels: 크루스칼

#464 [240528] BOJ 14621 나만 안되는 연애
  wnso-kim/Week_19/BOJ_14621_나만안되는연애/BOJ_14621_나만안되는연애.java
  wnso-kim/Week_19/BOJ_14621_나만안되는연애/BOJ_14621_나만안되는연애.md
Labels: 프림

#461 [240528] BOJ 14621 나만 안되는 연애
  u1qns/Week_19/BOJ_14621_나만 안되는 연애.java
Labels: 크루스칼

#459 [240528] BOJ 14621 나만 안되는 연애
  ys4512558/Week_19/BOJ_14621_나만안되는연애/BOJ_14621_나만안되는연애.java
  ys4512558/Week_19/BOJ_14621_나만안되는연애/BOJ_14621_나만안되는연애.md
Labels: 크루스칼

#472 [240528] BOJ 14621 나만 안되는 연애
  sjhlko/week19/BOJ_14621/BOJ_14621_나만안되는연애.java
Labels: 크루스칼

#470 [240528] BOJ 14621 나만 안되는 연애
  yunva17/Week_19/BOJ_14621_나만안되는연애/BOJ_14621_나만안되는연애.js
Labels: 크루스칼

#460 [240528] BOJ 14621 나만 안되는 연애
  ezeun/Week_19/BOJ_14621_나만안되는연애/BOJ_14621_나만안되는연애.cpp
  ezeun/Week_19/BOJ_14621_나만안되는연애/BOJ_14621_나만안되는연애.md
Labels: DFS, 크루스칼

#462 [240528] BOJ 14621 나만 안되는 연애
  sickbirdd/Week_19/BOJ_14621_나만 안되는 연애.java
  sickbirdd/Week_19/BOJ_14621_나만 안되는 연애.md
  sickbirdd/Week_19/BOJ_17780_새로운 게임.java
  sickbirdd/Week_19/BOJ_17780_새로운 게임.md
Labels: 크루스칼

#468 [240528] BOJ 14621 나만 안되는 연애
  trankill1127/w19/BOJ_14621.java
Labels: 크루스칼, 프림

#473 [240529] BOJ 17780 새로운 게임
  seoyoung059/Week_19/BOJ_17780/BOJ_17780.java
  seoyoung059/Week_19/BOJ_17780/BOJ_17780.md
Labels: 구현

#477 [240529] BOJ 17780 새로운 게임
  wnso-kim/Week_19/BOJ_17780_새로운게임/BOJ_17780_새로운게임.java
  wnso-kim/Week_19/BOJ_17780_새로운게임/BOJ_17780_새로운게임.md
Labels: 구현, 시뮬레이션

#475 [240529] BOJ 17780 새로운 게임
  u1qns/Week_19/BOJ_17780_새로운 게임.cpp
Labels: 구현

#481 [240529] BOJ 17780 새로운 게임
  sjhlko/week19/BOJ_17780/BOJ_17780_새로운게임_Refactor.java
Labels: 구현

#466 [240529] BOJ 17780 새로운 게임
  hyunseok0314/Week_19/BOJ_17609_회문.py
  hyunseok0314/Week_19/BOJ_17780_새로운_게임.java
Labels: 구현

#478 [240529] BOJ 17780 새로운 게임
  violetadieu/Week_19/17780_새로운게임.py
Labels: 구현

#479 [240529] BOJ 17780 새로운 게임
  trankill1127/w19/BOJ_17780.java
Labels: 구현
