Repository BE-Archive/Algorithm-Study, pull requests merged in 2024-08, with the labels that each got.

#786 [240802] BOJ 1743 음식물 피하기
  trankill1127/w28/BOJ_1743.java
Labels: BFS

#787 [240802] BOJ 1743 음식물 피하기
  yunva17/Week_28/BOJ_1743_음식물피하기/BOJ_1743_음식물피하기.js
Labels: BFS

#797 [240819] BOJ 12869 뮤탈리스크
  ys4512558/Week_31/BOJ_12869_뮤탈리스크/BOJ_12869_뮤탈리스크.java
  ys4512558/Week_31/BOJ_12869_뮤탈리스크/BOJ_12869_뮤탈리스크.md
Labels: BFS

#796 [240819] BOJ 12869 뮤탈리스크
  seoyoung059/Week_30/BOJ_12869/BOJ_12869.java
  seoyoung059/Week_30/BOJ_12869/BOJ_12869.md
Labels: DFS, 백트래킹

#798 [240820] SWEA 삼국지 게임
  trankill1127/w31/SWEA_삼국지_게임.java
Labels: 유니온 파인드, 자료구조

#803 [240821] SWEA AI로봇
  wnso-kim/Week_31/SWEA_AI로봇/SWEA_AI로봇.java
  wnso-kim/Week_31/SWEA_AI로봇/SWEA_AI로봇.md
Labels: 자료구조

#808 [240826] BOJ 1525 퍼즐
  sjhlko/week29/BOJ_1525/Main.java
Labels: BFS

#810 [240826] BOJ 1525 퍼즐
  l-umi/Week_32/BOJ_1525_퍼즐.py
Labels: BFS

#809 [240826] BOJ 1525 퍼즐
  u1qns/Week_29/BOJ_1525_퍼즐.cpp
Labels: BFS

#812 [240828] BOJ 14271 그리드 게임
  wnso-kim/Week_32/BOJ_14271_그리드_게임/BOJ_14271_그리드_게임.java
  wnso-kim/Week_32/BOJ_14271_그리드_게임/BOJ_14271_그리드_게임.md
Labels: BFS
